# Theme file for hyprtoolkit (used by hyprlauncher)
# Ref: https://wiki.hypr.land/Hypr-Ecosystem/hyprtoolkit/

font_family = JetBrainsMonoNL Nerd Font Mono
font_size = 14
rounding_large = 15
rounding_small = 5
