-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        rounding_power = 4.5,
    },
    general = {
        allow_tearing = true,
        layout = "scrolling",
        snap = {
            enabled = true,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Bezier curves
hl.curve("easeInOutExpo", { type = "bezier", points = { {0.87, 0.0}, {0.13, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6.0,
    bezier = "easeInOutExpo",
    style = "slide smart",
})
