-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Add config directory to search path
local home = os.getenv("HOME")
if home then
    package.path = home .. "/.config/hypr/modules/?.lua;" .. home .. "/.config/hypr/modules/?/init.lua;" .. package.path
end

-- Load modular configurations
require("monitors")
require("env")
require("permissions")
require("look_and_feel")
require("layouts")
require("keybinds")
require("rules")
require("autostart")
