-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    decoration = {
        rounding_power = 4.5,
    },
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
    general = {
        allow_tearing = true,
        layout = "scrolling",
        snap = {
            enabled = true,
        },
    },
    gestures = {
        workspace_swipe_cancel_ratio = 0.2,
        workspace_swipe_direction_lock = false,
        workspace_swipe_distance = 250,
        workspace_swipe_forever = true,
        workspace_swipe_min_speed_to_force = 10,
        workspace_swipe_use_r = false,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Bezier curves
hl.curve("easeInOutExpo", { type = "bezier", points = { {0.87, 0.0}, {0.13, 1.0} } })
hl.curve("easeOutExpo", { type = "bezier", points = { {0.16, 1.0}, {0.3, 1.0} } })

-- Animations
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutExpo",
    style = "gnomed",
})
hl.animation({
    leaf = "borderangle",
    enabled = false,
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6.0,
    bezier = "easeInOutExpo",
    style = "slide smart",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
